kind: ReplicaSet
apiVersion: apps/v1
#for deployment particular value is given for api like apps/v1
metadata:
  name: nginx-daemonsets
  namespace: nginx
spec:
  
  selector:
    matchLabels:
      app: nginx
        #selector is used to select the pod which contains label of nginx to create a replica

  template:
    metadata:
      name: nginx-dmn-pod
      labels:
        app: nginx
          #template is for pod 

    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80


# we can avoid creating pod.yml
# we can specify in deployment.yml file also under template and spec list
