kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
# as it is pod it should be located in namespace
  namespace: nginx
#spec will contain specifications about pods
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80


